DROP DATABASE IF EXISTS bd;
CREATE DATABASE bd;
USE bd;

CREATE TABLE JUGADOR(
  	NOMBRE VARCHAR(50),
  	ID INT NOT NULL,
  	PASS VARCHAR(15) NOT NULL,
  	VICTORIAS INT,
  	CARRERINES INT, /*Carrerines son las carreras jugadas*/
  	CIRCUITOFAV VARCHAR(50), /*El más jugado por ese jugador*/
  	TIEMPOTOTALJUGADO VARCHAR(20),
	PRIMARY KEY(ID)
	)ENGINE= InnoDB;

CREATE TABLE CARRERIN(
	ID INT NOT NULL,
	DURACION VARCHAR(20),
	GANADOR VARCHAR(50),
	CIRCUITO VARCHAR(50),
	VUELTARAPIDA VARCHAR (15),
	PRIMARY KEY(ID)
	)ENGINE = InnoDB; 

CREATE TABLE PARTICIPACION(
	ID INT NOT NULL,   
	IDCARRERIN INT NOT NULL,
	FOREIGN KEY(ID) REFERENCES JUGADOR(ID),
	FOREIGN KEY(IDCARRERIN) REFERENCES CARRERIN(ID)	
	)ENGINE = InnoDB;

INSERT INTO JUGADOR VALUES("Jofer", 1, "UwU", 4, 15, "GP EETAC", "123:34:87");
INSERT INTO JUGADOR VALUES("Oriol", 2, "Arigato", 1, 37, "GP TORRE", "564:33:12");

INSERT INTO CARRERIN VALUES(7, "6:33:12", "Jofer", "GP EETAC", "1:09:23");
INSERT INTO CARRERIN VALUES(6, "8:21:56", "Oriol", "GP TORRE", "1:56:34");

INSERT INTO PARTICIPACION VALUES (1, 7);
INSERT INTO PARTICIPACION VALUES (2, 6);