DROP DATABASE IF EXISTS M2_bd;
CREATE DATABASE M2_bd;
USE M2_bd;

CREATE TABLE JUGADOR(
      NOMBRE VARCHAR(50) NOT NULL,
      PASS VARCHAR(15) NOT NULL,
      VICTORIAS INT,
      CARRERINES INT, /*Carrerines son las carreras jugadas*/
      CIRCUITOFAV VARCHAR(50), /*El más jugado por ese jugador*/
      TIEMPOTOTALJUGADO VARCHAR(20),
    PRIMARY KEY(NOMBRE)
    )ENGINE= InnoDB;

CREATE TABLE CARRERIN(
    ID INT NOT NULL AUTO_INCREMENT,
    DISTANCIA INT,
    GANADOR VARCHAR(50),
    CIRCUITO VARCHAR(50),
    VUELTARAPIDA VARCHAR (15),
    PRIMARY KEY(ID)
    )ENGINE = InnoDB; 

CREATE TABLE PARTICIPACION(
    NOMBRE VARCHAR(50) NOT NULL,
    IDCARRERIN INT NOT NULL,
    FOREIGN KEY(NOMBRE) REFERENCES JUGADOR(NOMBRE),
    FOREIGN KEY(IDCARRERIN) REFERENCES CARRERIN(ID)
    )ENGINE = InnoDB;

INSERT INTO JUGADOR VALUES("Jofer", "UwU", 4, 15, "GP EETAC", "123:34:87");
INSERT INTO JUGADOR VALUES("Oriol", "Arigato", 1, 37, "GP TORRE", "564:33:12");

INSERT INTO CARRERIN VALUES(7, 1230, "Jofer", "GP EETAC", "1:09:23");
INSERT INTO CARRERIN VALUES(6, 3333, "Oriol", "GP TORRE", "1:56:34");

INSERT INTO PARTICIPACION VALUES ("Jofer", 7);
INSERT INTO PARTICIPACION VALUES ("Oriol", 6);
